info:
  contact: {}
paths:
  /products:
    post:
      consumes:
      - application/json
      description: Create product
      produces:
      - application/json
      responses: {}
      summary: Create product
      tags:
      - product
swagger: "2.0"
